Get http://localhost:3000/threads

###

Get http://localhost:3000/threads/62497069eeb436c315c526d8

###

Post http://localhost:3000/threads 
Content-Type: application/json 

{
    
    "rubrik": "Varför är alla tjocka på Tinder ?",
    "svar": "Då är väl Tinder en sida för överviktiga.",
    "like": "1"
} 

###
DELETE http://localhost:3000/threads/624b1ca22661ab29b8dfb24d   


###
Get http://localhost:3000/threads/624b1c035f64bc275f4a3736/replies


###
Post http://localhost:3000/threads/624b1c035f64bc275f4a3736/replies
Content-Type: application/json 

{
    
    "svar": "ett nytt svar",
} 

###
post http://localhost:3000/users
Content-Type: application/json 

{
    "username": "dana",
    "password": "password"
}

###
get http://localhost:3000/users